# Program to iterate over rows and columns in pandas dataframe

In [29]:
import pandas as pd
df=pd.read_csv("data1.csv")
display(df)
print("\n Iterrows Function")
for index,row in df.iterrows():
    print(index,row.Calories<400)
print("\n Itertuples Function\n")
for row in df.itertuples():
    
    print(row.Pulse>110 & row.Pulse<140)
print("\nIteritems Function\n")
for key,value in df.iteritems():
    print('Key : ',key)
    print('Values : ',value.values)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1

 Iterrows Function
0 False
1 False
2 True
3 True
4 False
5 True
6 True
7 True
8 True

 Itertuples Function

False
True
True
True
True
False
False
False
True

Iteritems Function

Key :  Duration
Values :  [60 60 60 45 45 60 60 45 30]
Key :  Pulse
Values :  [110 117 103 109 117 102 110 104 109]
Key :  Maxpulse
Values :  [130 145 135 175 148 127 136 134 133]
Key :  Calories
Values :  [409.1 479.  340.  282.4 406.  300.  374.  253.3 195.1]